---
# Setup macOS defaults to configure most of OS level configurations
configure_osx: true

# Set to true to enable setting the hostname for the machine
configure_hostname: true

# Set to true to run mackup tasks for preferences and settings backup/restore
configure_mackup: true

# Set to true to run ohmyzsh installation
configure_ohmyzsh: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- Launchpad
- Maps
- FaceTime
- Contacts
- Freeform
- TV
- News
- 'App Store'
- 'System Settings'
dockitems_persist:
- name: "Music"
  path: "/System/Applications/Music.app/"
  pos: 1
- name: "Photos"
  path: "/System/Applications/Photos.app/"
  pos: 2
- name: "Shortcuts"
  path: "/System/Applications/Shortcuts.app/"
  pos: 3
- name: "Safari"
  path: "/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/"
  pos: 4
- name: "Google Chrome"
  path: "/Applications/Google Chrome.app/"
  pos: 5
- name: "Mail"
  path: "/System/Applications/Mail.app/"
  pos: 6
- name: "Calendar"
  path: "/System/Applications/Calendar.app/"
  pos: 7
- name: "Zoom"
  path: "/Applications/zoom.us.app/"
  pos: 8
- name: "Slack"
  path: "/Applications/Slack.app/"
  pos: 9
- name: "Discord"
  path: "/Applications/Discord.app/"
  pos: 10
- name: "Messages"
  path: "/System/Applications/Messages.app/"
  pos: 11
- name: "Reminders"
  path: "/System/Applications/Reminders.app/"
  pos: 12
- name: "Notes"
  path: "/System/Applications/Notes.app/"
  pos: 13
- name: "Obsidian"
  path: "/Applications/Obsidian.app/"
  pos: 14
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 15
- name: "Terminal"
  path: "/System/Applications/Utilities/Terminal.app/"
  pos: 16

# Install dotfiles from designated repo
configure_dotfiles: false
dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .osx
  - .gitignore

# Install core homebrew packages (formulae)
configure_homebrew: true
homebrew_packages:
  # look back into packages from geerlingguy original
  - awscli
  - helm
  - kubernetes-cli
  - mackup
  - neofetch
  - switchaudio-osx
  - terraform
  # these are at the end to avoid popups during installs
  - mas
  # Install cask apps, most of the usual apps to be installed here
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - alfred
  - android-file-transfer
  # - ansible # listing here for reference, but should be installed in bootstrap.sh
  - appcleaner
  - arc
  - balenaetcher
  - blender
  - clickup
  - cyberduck
  - dash
  - discord
  - disk-inventory-x
  - docker
  - hpedrorodrigues/tools/dockutil
  - drawio
  - firefox
  - google-chrome
  - handbrake
  - home-assistant
  - icanhazshortcut
  - keka
  - keybase
  - knockknock
  - licecap
  - mactracker
  - microsoft-teams
  - mullvadvpn
  - obs
  - obsidian
  - openscad
  - pgadmin4
  - postman
  - powershell
  - prusaslicer
  - raycast
  - rocket-chat
  - sequel-ace
  - session-manager-plugin
  - shottr
  - shuttle
  - slack
  - stats
  - subler
  - suspicious-package
  - taskexplorer
  - teamviewer
  - the-unarchiver
  - tor-browser
  - utm
  - vanilla
  - virtualbox
  - visual-studio-code
  - vlc
  - wireshark
  - zoom
  # these are at the end to avoid popups during installs
  - lulu
  - blockblock

# Install Mac App Store apps
configure_mas: true
mas_apps:
  # Safari plugins
  - 1569813296  # 1Password for Safari
  - 1546729687  # Auto HD FPS for YouTube
  - 1482920575  # DuckDuckGo Privacy for Safari
  - 1472777122  # PayPal Honey
  - 1463298887  # Userscripts
  # macOS Apps
  - 937984704   # Amphetamine
  - 413969927   # AudioBookBinder
  - 425264550   # Disk Speed Test
  - 1142151959  # Just Focus
  - 1295203466  # Microsoft Remote Desktop
  - 419330170   # Moom
  - 1475387142  # Tailscale
  - 1482454543  # Twitter
  - 497799835   # Xcode
