- name: Configure macOS Host
  hosts: localhost
  connection: local

  vars_files:
    - config.yml

  vars_prompt:
    - name: user_account
      prompt: Please enter your user account name so we can insert the home directory
      private: false
    - name: ansible_become_password
      prompt: Please enter your user password for sudo escalations
      private: true
      confirm: true
      unsafe: true


  # roles:
  #   - role: geerlingguy.mac.homebrew
  #     tags: ['homebrew']
  #   - role: geerlingguy.mac.mas
  #     when: mas_installed_apps or mas_installed_app_ids
  #     tags: ['mas']
  #   - role: geerlingguy.dotfiles
  #     when: configure_dotfiles
  #     tags: ['dotfiles']
  #   - role: geerlingguy.mac.dock
  #     when: configure_dock
  #     tags: ['dock']

  tasks:
    - import_tasks: tasks/homebrew.yml
      when: configure_homebrew
      tags: ['homebrew']
    - import_tasks: tasks/mas.yml
      when: configure_mas
      tags: ['mas']
    - import_tasks: tasks/osx_defaults.yml
      when: configure_osx
      tags: ['osx']
    - import_tasks: tasks/mackup.yml
      when: configure_mackup
      tags: ['mackup']
  
  handlers:
    # Handler for killing Dock from OSX Defaults changes to Dock
  - name: Kill dock
    shell: killall Dock
    changed_when: false
    # Handler for killing Safari from OSX Defaults changes to Safari
  - name: Kill Safari
    shell: killall Safari
    changed_when: false
    # Handler for killing Finder from OSX Defaults changes to Finder
  - name: Kill Finder
    shell: killall Finder
    changed_when: false

  post_tasks:
  # TODO Add manual intervention for apps that need to be opened for example or launched
    - import_tasks: tasks/updates.yml
      tags: ['update','post']