- name: Configure macOS Host
  hosts: localhost
  connection: local

  vars_files:
    - config.yml

  vars_prompt:
    - name: user_account
      prompt: Please enter your user account name so we can insert the home directory
      private: false
    - name: new_hostname
      prompt: Please enter your desired hostname for this machine
      private: false
    - name: ansible_become_password
      prompt: Please enter your user password for sudo escalations
      private: true
      confirm: true
      unsafe: true

  tasks:
    - ansible.builtin.import_tasks: tasks/hostname.yml
      when: configure_hostname
      tags: ['hostname']
    - ansible.builtin.import_tasks: tasks/homebrew.yml
      when: configure_homebrew
      tags: ['homebrew']
    - ansible.builtin.import_tasks: tasks/mas.yml
      when: configure_mas
      tags: ['mas']
    - ansible.builtin.import_tasks: tasks/osx_defaults.yml
      when: configure_osx
      tags: ['osx']
    - ansible.builtin.import_tasks: tasks/mackup.yml
      when: configure_mackup
      tags: ['mackup']
    - ansible.builtin.import_tasks: tasks/dock.yml
      when: configure_dock
      tags: ['dock']

  handlers:
    # Handler for killing Dock from OSX Defaults changes to Dock
  - name: Kill dock
     ansible.builtin.shell: killall Dock
    changed_when: false
    # Handler for killing Safari from OSX Defaults changes to Safari
  - name: Kill Safari
     ansible.builtin.shell: killall Safari
    changed_when: false
    # Handler for killing Finder from OSX Defaults changes to Finder
  - name: Kill Finder
     ansible.builtin.shell: killall Finder
    changed_when: false

  post_tasks:
  # TODO Add manual intervention for apps that need to be opened for example or launched
    - ansible.builtin.import_tasks: tasks/updates.yml
      tags: ['update','post']