---
# Reference for Module: https://docs.ansible.com/ansible/latest/collections/community/general/git_config_module.html


# [filter "lfs"]
# 	clean = git-lfs clean -- %f
# 	smudge = git-lfs smudge -- %f
# 	required = true
# 	process = git-lfs filter-process
# [user]
# 	name = 1activegeek
# 	email = 
# [credential]
# 	helper = osxkeychain
# [pull]
# 	rebase = false