---
# Reference for module: https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_module.html#examples

# Update Homebrew on every run to ensure it's up to date
- name: Update homebrew
  homebrew:
    update_homebrew: true

# Install the packages that are core formulae vs casks - iterating through each in a loop to see status
- name: Install Homebrew packages
  homebrew:
    name: "{{ item.name | default(item) }}"
    state: present
  loop: "{{ homebrew_packages }}"

# Install the casks apps
- name: Install Homebrew casks
  homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  loop: "{{ homebrew_cask_apps }}"
  ignore_errors: true