---
# Reference for manual creation: https://github.com/lra/mackup/tree/master/doc#get-official-support-for-an-application
# Issue found in macOS Sonoma: https://github.com/lra/mackup/issues/1924#issuecomment-1756330534
# causing issues with apps keeping their settings at all

# Checking to see if the mackup config file exists
- name: Check for mackup config file
  stat:
    path: ~/.mackup.cfg
  register: stat_result
# If it doesn't exist, set its content to use iCloud and set destination folder
- name: Creating mackup config file
  shell: echo "[storage]" > ~/.mackup.cfg && echo "engine = icloud" >> ~/.mackup.cfg && echo "directory = mackup" >> ~/.mackup.cfg
  when: not stat_result.stat.exists
# # If it doesn't exist, copy it over from the repo content
# - name: Placing mackup config file in Home directory
#   command: cp ./mackup.cfg ~/mackup.cfg
#   when: not stat_result.stat.exists
# Running mackup restore function to restore configurations
- name: Running mackup restore function
  command: mackup restore -f && mackup uninstall --force


## Mackup Apps
  # - Microsoft Remote Desktop
  # - Moom
  # - XCode
  # - awscli
  # - kubectl
  # - neofetch
  # - 1password
  # - appcleaner
  # - blender
  # - cyberduck
  # - dash
  # - docker
  # - handbrake
  # - keka
  # - keybase
  # - obs
  # - prusaslicer
  # - raycast
  # - shuttle
  # - visual-studio-code
  # - vlc
  # - wireshark

## Apps Needing Configs potentially
# Homebrew
# - helm
# - terraform
# - discord
# - icanhazshortcut
# - knockknock
# - mullvadvpn
# - obsidian
# - postman
# - powershell
# - shottr
# - slack
# - teamviewer
# - vanilla
# - zoom
# - lulu
# - blockblock

# MAS
# - Amphetamine
# - Tailscale
# - Twitter