---
# Reference for Module: https://docs.ansible.com/ansible/latest/collections/community/general/osx_defaults_module.html#ansible-collections-community-general-osx-defaults-module

## Dock
- name: Set dock tile size
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 60
    state: present
  notify:
  - Kill dock
- name: Set dock magnification size
  osx_defaults:
    domain: com.apple.dock
    key: largesize
    type: float
    value: 80
    state: present
  notify:
  - Kill dock
- name: Minimize windows into application icon
  osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
    state: present
  notify:
  - Kill dock
- name: Automatically hide and show the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    state: present
  notify:
  - Kill dock
- name: Show recent applications in Dock
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
    state: present
  notify:
  - Kill dock
- name: Rearrange spaces based on use
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: true
    state: present
  notify:
  - Kill dock
## Trackpad
- name: Turn off Natural Scrolling
  osx_defaults:
    key: com.apple.swipescrolldirection
    type: bool
    value: false
    state: present
- name: Enable tap to click
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: int
    value: 1
    state: present
- name: Disable Prefer Nicknames on Contacts
  osx_defaults:
    key: NSPersonNameDefaultShouldPreferNicknamesPreference
    type: int
    value: 0
    state: present
## Safari
- name: Show Develop Menu in Safari
  osx_defaults:
    domain: com.apple.Safari.SandboxBroker
    key: ShowDevelopMenu
    type: bool
    value: true
    state: present
  notify:
  - Kill Safari
## Finder
- name: Show Internal Hard Drives on Desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: true
    state: present
  notify:
  - Kill Finder
- name: Show Finder Status Bar
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
    state: present
  notify:
  - Kill Finder
- name: Set default Finder new window location
  osx_defaults:
      domain: com.apple.finder
      key: NewWindowTarget
      type: string
      value: PfLo
      state: present
  notify:
  - Kill Finder
####### NEED TO FIX THIS TO ADJUST USING HOME DIRECTORY OF USER #########
- name: Set default Finder new window location Folder
  osx_defaults:
      domain: com.apple.finder
      key: NewWindowTargetPath
      type: string
      value: file:///Users/{{ user_account }}/Downloads
      state: present
  notify:
  - Kill Finder
- name: Set default search scope to Current Folder
  osx_defaults:
      domain: com.apple.finder
      key: FXDefaultSearchScope
      type: string
      value: SCcf
      state: present
  notify:
  - Kill Finder
- name: Remove items from Trash after 30 days
  osx_defaults:
      domain: com.apple.finder
      key: FXRemoveOldTrashItems
      type: bool
      value: true
      state: present
  notify:
  - Kill Finder
- name: Keep folders on top in Windows when sorting
  osx_defaults:
      domain: com.apple.finder
      key: "_FXSortFoldersFirst"
      type: bool
      value: true
      state: present
  notify:
  - Kill Finder
## Audio
- name: Play feedback when adjusting volume
  osx_defaults:
      domain: NSGlobalDomain
      key: com.apple.sound.beep.feedback
      type: int
      value: 1
      state: present


# - osx_defaults:
#     domain: com.
#     key: 
#     type:
#     value:
#     state: present
#   become: true

