# Upgrade all cask apps to ensure we keep them up to date
- name: Upgrade all Homebrew casks
  homebrew_cask:
    upgrade_all: true
    sudo_password: "{{ ansible_become_password }} | default(omit)"

# Upgrade all homebrew packages when running to ensure we keep apps up to date
# Placing this after Casks, so that sudo_password can be used for casks
- name: Upgrade all Homebrew packages
  homebrew:
    upgrade_all: true

# Upgrade all macOS Apps from the App Store
- name: Upgrade all installed Mac App Store apps
  mas:
    upgrade_all: true